---

- name: Request SSL certificates for GitLab from Let's Encrypt
  docker_container:
    name: letsencrypt-init-git
    image: quay.io/letsencrypt/letsencrypt:latest
    state: started
    ports:
     - "443:443"
     - "80:80"
    volumes:
     - "/opt/docker-containers/letsencrypt/etc/letsencrypt:/etc/letsencrypt"
     - "/opt/docker-containers/letsencrypt/var/lib/letsencrypt:/var/lib/letsencrypt"
    command: certonly --standalone --agree-tos --renew-by-default -d {{ nginx_git_domain_name }} -m {{ nginx_git_domain_contact_email }}

- pause:

- name: Request SSL certificates for Docker Registry from Let's Encrypt
  docker_container:
    name: letsencrypt-init-registry
    image: quay.io/letsencrypt/letsencrypt:latest
    state: started
    ports:
     - "443:443"
     - "80:80"
    volumes:
     - "/opt/docker-containers/letsencrypt/etc/letsencrypt:/etc/letsencrypt"
     - "/opt/docker-containers/letsencrypt/var/lib/letsencrypt:/var/lib/letsencrypt"
    command: certonly --standalone --agree-tos --renew-by-default -d {{ nginx_registry_domain_name }} -m {{ nginx_registry_domain_contact_email }}
